// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import DefilementCardController from "./defilement_card_controller"
application.register("defilement-card", DefilementCardController)

import DefilementImgController from "./defilement_img_controller"
application.register("defilement-img", DefilementImgController)

import DefilementImgShowController from "./defilement_img_show_controller"
application.register("defilement-img-show", DefilementImgShowController)

import DefilementIngredientShowController from "./defilement_ingredient_show_controller"
application.register("defilement-ingredient-show", DefilementIngredientShowController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import MapController from "./map_controller"
application.register("map", MapController)

import SubmitItemController from "./submit_item_controller"
application.register("submit-item", SubmitItemController)
